---
title: Pi
timezone: Asia/Ho_Chi_Minh
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: x2happi@gmail.com
facebook: XX2Pi
description: My blog
baseurl: ''
url: x2pi.github.io
github_username: x2pi
markdown: kramdown
permalink: pretty
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
