# Site settings
title: Pi
email: x2happi@gmail.com
facebook: "XX2Pi"
description: "My blog"
baseurl: ""
url: "x2pi.github.io"
github_username:  x2pi

# Build settings
timezone: Asia/Ho_Chi_Minh
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
  hard_wrap: false
